version: "3.3"
services:
    web_server:
        hostname: web_server
        build:
            context: ./cotizacion-bna
        
        ports:
            - 5000:5000
    script:
        depends_on:
            - web_server
        build:
            context: ./script
        hostname: script
        restart: always
        volumes:
          - ./script:/app/script
